name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3.1.1
        with:
          node-version: lts/*
      - name: Install
        run: npm install --no-package-lock
      - name: Test
        run: npm test
      - name: Report
        run: mkdir -p coverage && npx c8 report --reporter=text-lcov > coverage/lcov.info
      - name: Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
